package com.china.bosh.mylibrary.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.china.bosh.mylibrary.db.table.PriceEntity;
import com.china.bosh.mylibrary.db.table.tableTest;

import com.china.bosh.mylibrary.db.PriceEntityDao;
import com.china.bosh.mylibrary.db.tableTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig priceEntityDaoConfig;
    private final DaoConfig tableTestDaoConfig;

    private final PriceEntityDao priceEntityDao;
    private final tableTestDao tableTestDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        priceEntityDaoConfig = daoConfigMap.get(PriceEntityDao.class).clone();
        priceEntityDaoConfig.initIdentityScope(type);

        tableTestDaoConfig = daoConfigMap.get(tableTestDao.class).clone();
        tableTestDaoConfig.initIdentityScope(type);

        priceEntityDao = new PriceEntityDao(priceEntityDaoConfig, this);
        tableTestDao = new tableTestDao(tableTestDaoConfig, this);

        registerDao(PriceEntity.class, priceEntityDao);
        registerDao(tableTest.class, tableTestDao);
    }
    
    public void clear() {
        priceEntityDaoConfig.clearIdentityScope();
        tableTestDaoConfig.clearIdentityScope();
    }

    public PriceEntityDao getPriceEntityDao() {
        return priceEntityDao;
    }

    public tableTestDao getTableTestDao() {
        return tableTestDao;
    }

}
