package com.china.bosh.mylibrary.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.china.bosh.mylibrary.db.table.tableTest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TABLE_TEST".
*/
public class tableTestDao extends AbstractDao<tableTest, Integer> {

    public static final String TABLENAME = "TABLE_TEST";

    /**
     * Properties of entity tableTest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", true, "ID");
        public final static Property Property = new Property(1, String.class, "property", false, "PROPERTY");
    }


    public tableTestDao(DaoConfig config) {
        super(config);
    }
    
    public tableTestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TABLE_TEST\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"PROPERTY\" TEXT);"); // 1: property
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TABLE_TEST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, tableTest entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String property = entity.getProperty();
        if (property != null) {
            stmt.bindString(2, property);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, tableTest entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String property = entity.getProperty();
        if (property != null) {
            stmt.bindString(2, property);
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public tableTest readEntity(Cursor cursor, int offset) {
        tableTest entity = new tableTest( //
            cursor.getInt(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // property
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, tableTest entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setProperty(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(tableTest entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(tableTest entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(tableTest entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
